name: Fetch all roles

on:
  workflow_dispatch:
  schedule:
    - cron: "44 */12 * * *"
    
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@main
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: set gcp project
      run: gcloud config set project darkbit-audit-resources
    - name: fetch all iam roles
      run: ./fetch-all-roles.sh
    - name: commit, tag, and release
      run: ./.github/commit-and-release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
